<?php

namespace AppBundle\Repository;

/**
 * BuyingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BuyingRepository extends \Doctrine\ORM\EntityRepository
{
}
