<?php

namespace AppBundle\Repository;

/**
 * Categories_kitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Categories_kitRepository extends \Doctrine\ORM\EntityRepository
{
}
