<?php

namespace AppBundle\Repository;

/**
 * EquimentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EquimentRepository extends \Doctrine\ORM\EntityRepository
{
}
