<?php

namespace AppBundle\Repository;

/**
 * ReplacementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReplacementRepository extends \Doctrine\ORM\EntityRepository
{
}
