<?php

namespace AppBundle\Repository;

/**
 * SearchesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SearchesRepository extends \Doctrine\ORM\EntityRepository
{
}
