admin_categories_kit_index:
    path:     /
    defaults: { _controller: "AppBundle:Categories_kit:index" }
    methods:  GET

admin_categories_kit_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Categories_kit:show" }
    methods:  GET

admin_categories_kit_new:
    path:     /new
    defaults: { _controller: "AppBundle:Categories_kit:new" }
    methods:  [GET, POST]

admin_categories_kit_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Categories_kit:edit" }
    methods:  [GET, POST]

admin_categories_kit_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Categories_kit:delete" }
    methods:  DELETE
