AppBundle\Entity\Brands:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\BrandsRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '65'
        logo:
            type: string
            length: 255
        createdAt:
            type: datetime
            column: created_at
    lifecycleCallbacks: {  }
